[package]
name = "nanilang"
version = "0.1.0"
authors = ["Tiago Nascimento <tiago@theosirian.com>", "Guilherme Chichanoski <ra82174@uem.br>"]

[build-dependencies]
lalrpop = "0.16.1"

[dependencies]
lalrpop-util = "0.16.1"
clap = "2.32.0"
regex = "0.2.1"
llvm-sys = "60"
