[package]
name = "nanilang"
version = "0.1.0"
authors = ["Tiago Nascimento <tiago@theosirian.com>"]

[build-dependencies]
lalrpop = "0.16.1"

[dependencies]
lalrpop-util = "0.16.1"
regex = "0.2.1"
getopts = "0.2.18"
llvm-sys = "60"
